```{r   }
library(MedicalRiskPredictionModels)
dataMRPM() 
```

```{r   }
# Chunk2
# logistic regression in learn data
nullmodel <- glm(ohss~1,data=ivftrain,family="binomial") 
# predicted risk in test data
ivftest[,risk.null:=predictRisk(nullmodel,newdata=ivftest)]
# result does not depend on predictor variables
ivftest[1:5,.(cyclelen,bmi,age,smoking,ant.foll,risk.null)] 
```

```{r   }
# Chunk3
library(riskRegression)
# Kaplan-Meier estimate in training set
km <- prodlim(Hist(survtime,survstatus)~1,data=octrain)
# Predicted risk at 5 and 10 years in test set
octest[,km.risk5:=predictRisk(km,newdata=octest,times=60)]
octest[,km.risk10:=predictRisk(km,newdata=octest,times=120)]
# Predicted risks do not depend on predictor variables
octest[1:5,.(age,gender,tobacco,tumorthickness,km.risk5,km.risk10)] 
```

```{r   }
# Chunk4
library(riskRegression)
# Aalen-Johansen estimate in training set
aj <- prodlim(Hist(asprogtime,asprog)~1,data=astrain)
# Predict the risks at 3 year horizon in the test set
astest[,aj.progrisk3:=predictRisk(aj,newdata=astest,times=3,cause="progression")]
astest[,aj.deathrisk3:=predictRisk(aj,newdata=astest,times=3,cause="death")]
# Predicted risks do not depend on predictor variables
astest[1:5,.(age5,psa,ct1,diaggs,aj.progrisk3,aj.deathrisk3)] 
```

```{r   }
# Chunk5
fit <- glm(ohss~smoking,data=ivftrain,family="binomial")
publish(fit,intercept=1) 
```

```{r   }
# Chunk6
library(data.table)
fit <- glm(ohss~smoking,data=ivftrain,family="binomial")
nd <- data.table(smoking=c("No","Yes"))
nd[,risk.ohss:=predictRisk(fit,newdata=nd)]
nd 
```

```{r   }
# Chunk7
fit <- coxph(Surv(survtime, survstatus)~grade+gender,
             data=octrain,x=1)
publish(fit) 
```

```{r   }
# Chunk8
fit <- coxph(Surv(survtime, survstatus)~grade+gender,
             data=octrain,x=1)
nd <- data.table(expand.grid(grade=c("Well","Moderate","Poor"),gender=c("Male","Female")))
nd[,risk.10years:=predictRisk(fit,times=120,newdata=nd)]
nd 
```

```{r   }
# Chunk9
fit <- CSC(Hist(asprogtime,asprog)~diaggs+ct1,data=astrain)
publish(fit,diaggs="Gleason score",ct1="Clinical stage") 
```

```{r   }
# Chunk10
fit <- FGR(Hist(asprogtime,asprog)~diaggs+ct1,data=astrain,
           cause="progression")
publish(fit) 
```

```{r   }
# Chunk11
ivftrain[,age5:=age/5] # odds ratio per 5 year increase of age
fit <- glm(ohss~age5,data=ivftrain,family="binomial") 
```

```{r   }
# Chunk12
library(rms)
fit <- lrm(ohss~rcs(age),data=ivftrain) 
```

```{r   }
# Chunk13
library(rms)
# fit Cox regression models
fit1=cph(Surv(survtime,survstatus)~tumorthickness,
         data=octrain,x=1,y=1)
fit2=cph(Surv(survtime,survstatus)~lsp(tumorthickness,c(.5,1,3)),
         data=octrain,x=1,y=1)
fit3=cph(Surv(survtime,survstatus)~rcs(tumorthickness,3),
         data=octrain,x=1,y=1)
# select tumor thickness values for which to predict
nd=data.table(tumorthickness=c(0.1,.5,.75,seq(1,8,1)))
# extract 10 year predicted risks from Cox regression
R1=predictRisk(fit1, newdata=nd,times=120)
R2=predictRisk(fit2, newdata=nd,times=120)
R3=predictRisk(fit3, newdata=nd,times=120)
# put results in a table
nd[,"10-year risk linear":=100*R1]
nd[,"10-year risk linear spline":=100*R2]
nd[,"10-year risk cubic spline":=100*R3]
publish(nd,digits=1) 
```

```{r   }
# Chunk14
fit1 <- CSC(Hist(asprogtime,asprog)~psa+ct1+diaggs,data=astrain,cause="progression")
fit2 <- CSC(Hist(asprogtime,asprog)~psa*ct1+diaggs,data=astrain,cause="progression")
# select 12 examples
nd=expand.grid(diaggs=c("GNA","3 and 3","3 and 4"),
               ct1=c("cT1","cT2"),
               psa=c(-3,-1))
# predict 3-year risk of progression
R1 <- 100*predictRisk(fit1,newdata=nd,cause="progression",times=3)
R2 <- 100*predictRisk(fit2,newdata=nd,cause="progression",times=3)
cbind(nd,"No interaction term"=R1,"With interaction term"=R2) 
```

```{r   }
# Chunk15
fit1 <- glm(ohss~ant.foll+smoking+age,data=ivftrain,family="binomial")
fit2 <- glm(ohss~ant.foll*smoking+age,data=ivftrain,family="binomial")
# select 6 examples
nd <- expand.grid(ant.foll=c(10,30,50),
                  age=c(30),
                  smoking=factor(c("Yes","No")))
R1 <- 100*predictRisk(fit1,newdata=nd)
R2 <- 100*predictRisk(fit2,newdata=nd)
cbind(nd,"Without interaction term"=R1,"With interaction term"=R2) 
```

```{r   }
# Chunk16
library(rms)
fit1 <- lrm(ohss~rcs(ant.foll,3)+rcs(age,3)+rcs(cyclelen,3)+smoking,data=ivftrain)
fit2 <- lrm(ohss~rcs(ant.foll,3)+rcs(age,3)+rcs(cyclelen,3)+smoking,data=ivftrain,penalty=5)
fit3 <- lrm(ohss~rcs(ant.foll,3)+rcs(age,3)+rcs(cyclelen,3)+smoking,data=ivftrain,penalty=10)
# select 5 covariate patterns
nd=expand.grid(ant.foll=c(10,20),
               age=28,
               cyclelen=c(27,32),
               smoking="No")
# predict risks
R1=100*predictRisk(fit1,nd)
R2=100*predictRisk(fit2,nd)
R3=100*predictRisk(fit3,nd)
cbind(nd,"no penalty"=R1,"penalty 5"=R2,"penalty 10"=R3) 
```

```{r   }
# Chunk17
fit <- coxph(Surv(survtime,survstatus)~tumorthickness + age + gender * race * tobacco * site
            ,data=octrain,y=1,x=1) 
```

```{r   }
# Chunk18
tab1 <- summary(utable(gender~age+deep.invasion+tobacco+tumorthickness+grade,data=octrain,
                       summary.format="median(x) (IQR(x)) [range(x)]"),show.pvalue=0)
tab1 
```

```{r   }
# Chunk19
ivf[,set:=factor(train,levels=c(TRUE,FALSE),
                 labels=c("Training","Validation"))]
tab1 <- summary(utable(set~Q(age)+cyclelen+Q(bmi)+fsh+ant.foll+smoking,data=ivf),
                show.pvalues=0)
tab1 
```

```{r   }
# Chunk20
tab2 <- followupTable(Hist(asprogtime,asprog)~age+ct1+erg.status,data=as,followup.time=5)
tab2 
```

```{r   }
# Chunk21
fit <- coxph(Surv(survtime,survstatus)~age+gender+tumorthickness+grade,data=octrain)
publish(fit,probindex=TRUE) 
```

```{r   }
# Chunk22
fit <- ARR(Hist(asprogtime, asprog)~ct1+erg.status+age5+psa+ppb5+lmax,
           data=astrain, times=5, cause="progression")
publish(fit) 
```

```{r   }
# Chunk23 
fit <- lrm(ohss~age+rcs(ant.foll)+smoking,data=ivf)
plot(nomogram(fit,fun=function(x)1/(1+exp(-x)),  # or fun=plogis
              funlabel=paste0("Risk of OHSS"))) 
```

```{r   }
# Chunk24 
u <- datadist(octrain)
options(datadist="u")
fit <- cph(Surv(survtime,survstatus)~age*grade+gender+rcs(tumorthickness),
           data=octrain,
           surv=1)
surv <- Survival(fit)
nom <- nomogram(fit, fun=list(function(x) 1-surv(60, x),
                              function(x) 1-surv(120, x)),
                funlabel=c("5-year risk", 
                           "10-year risk"))
plot(nom, xfrac=.5) 
```

```{r   }
nm.bin <- glm(ohss~1,data=ivftrain,family="binomial")
cat("Training data set:\n")
ivftrain[,addmargins(table(ohss))]
ivftrain[,list("risk"=sprintf("%1.1f",100*prop.table(table(ohss))[2]))]
cat("Validation data set:\n")
ivftest[,addmargins(table(ohss))]
ivftest[,list("risk"=sprintf("%1.1f",100*prop.table(table(ohss))[2]))] 
```

```{r   }
Model11 <- glm(ohss~smoking,data=ivftrain,family="binomial")
publish(Model11,intercept=1,org=TRUE,digits=3) 
```

```{r   }
Model11 <- glm(ohss~smoking,data=ivftrain,family="binomial")
new.bin <- data.frame(smoking=factor(c("Yes","No")))
cat(sprintf("%1.1f",100*predictRisk(Model11,newdata=new.bin)),"\n") 
```

```{r   }
km <- prodlim(Hist(survtime,survstatus)~1,data=octrain)
cat(sprintf("%1.1f",100*predictRisk(km,times=120,newdata=data.frame(age=c(28,74),tumorthickness=c(0.3,0.1)))),"\n") 
```

```{r   }
Model21 <- coxph(Surv(survtime, survstatus)~grade+gender,data=octrain,x=TRUE)
publish(Model21,org=TRUE) 
```

```{r   }
Model21 <- coxph(Surv(survtime, survstatus)~grade+gender,data=octrain,x=TRUE)
new.surv <- expand.grid(grade=c("Well","Moderate","Poor"),gender=c("Male","Female"))
org(cbind(new.surv,"10-year risk"=sprintf("%1.1f",100*predictRisk(Model21,newdata=new.surv,times=120)))) 
```

```{r   }
Model22 <- coxph(Surv(survtime,survstatus)~tumorthickness,data=octrain,y=1L,x=1L)
org(Model22)
cat("\n")
nd=data.frame(tumorthickness=c(0.1,0.5,1,2,4))
org(cbind(nd,"10-year risk"=sprintf("%1.1f",100*predictRisk(Model22,newdata=nd,times=120)))) 
```

```{r   }
nm.cr <- prodlim(Hist(asprogtime,asprog)~1,data=astrain)
cat(sprintf("%1.1f",100*predictRisk(nm.cr,times=3,cause="progression",newdata=data.frame(age=c(28,74),psa=c(-1.3,-5.8)))),"\n") 
```

```{r   }
fit1 <- CSC(Hist(asprogtime,asprog)~psa+ct1+diaggs,data=astrain,cause="progression")
fit2 <- CSC(Hist(asprogtime,asprog)~psa*ct1+diaggs,data=astrain,cause="progression")
nd=expand.grid(diaggs=c("GNA","3 and 3","3 and 4"),ct1=c("cT1","cT2"),psa=c(-3,-1))
org(cbind(nd,"No interaction term"=sprintf("%1.1f",predictRisk(fit1,newdata=nd,cause="progression",times=3)),
      "With interaction term"=sprintf("%1.1f",predictRisk(fit2,newdata=nd,cause="progression",times=3)))) 
```

